### ISSUE TITLE
PHPCRSlideshowBlockAdmin  - error 500 when uploading multiple images

### ISSUE THREAD

**Issue by joiz** [symfony-cmf/block-bundle#247]
The user wants to create a slideshow with several pictures. Selects an image via "Choose file" and now tries to add another element to the list by "Add new". User now gets an error 500.

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
An exception has been thrown during the rendering of a template ("Parameter "path" for route "liip_imagine_filter" must match ".+" ("" given) to generate a corresponding URL.") in "CmfMediaBundle:Form:fields.html.twig" at line 9.

If you add images one by one and press save in between this works - but its not very practical

![slideshow-addnew](https://cloud.githubusercontent.com/assets/1535760/14741482/c31792ac-0896-11e6-98be-15396d983cb0.jpg)

![slideshow-addnew-error](https://cloud.githubusercontent.com/assets/1535760/14741485/c5e99c1e-0896-11e6-8744-471b983d731c.jpg)

**Comment by dbu** [comment]
afaik the problem is that sonata admin needs to submit and reload the
whole list of slides when you add a new one. but you don't save yet, so
they send data and re-send the form with the values as default - which
does not work well for images. it would be nicer if the add button could
somehow just add one new empty document instead of the roundtrip
solution. there might be a better solution under way with sonata 3, but
i am not in the loop.

googling around found me this documentation:

https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_file_uploads.html#advanced-example-works-with-embedded-admins

maybe this could be used here. maybe that could even be a bugfix for the
cmf block bundle. do you want to give it a try?

**Comment by joiz** [comment]
Thanks David, i will have a look

**Comment by dbu** [comment]
media bundle is not maintained anymore. and the admins moved to their own bundle.
